name: Deploy GoRide to VPS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          echo "🚀 Starting GoRide deployment..."
          
          cd /var/www/goride || exit 1
          git pull origin main
          
          cd laravel-backend
          composer install --no-dev --optimize-autoloader
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          
          sudo systemctl restart php8.2-fpm
          sudo systemctl restart goride-worker
          sudo systemctl reload nginx
          
          echo "✅ GoRide deployment completed!"
